namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmKetThucKhaoSat
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.tabKT = new System.Windows.Forms.TabControl();
            this.tpTT = new System.Windows.Forms.TabPage();
            this.tpKS = new System.Windows.Forms.TabPage();
            this.dgvDoan = new System.Windows.Forms.DataGridView();
            this.label1 = new System.Windows.Forms.Label();
            this.txtSoTT = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtSoDK = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.dtTT = new System.Windows.Forms.DateTimePicker();
            this.label4 = new System.Windows.Forms.Label();
            this.numTien = new System.Windows.Forms.NumericUpDown();
            this.label5 = new System.Windows.Forms.Label();
            this.txtGhiChu = new System.Windows.Forms.TextBox();
            this.btnThanhToan = new System.Windows.Forms.Button();
            this.label6 = new System.Windows.Forms.Label();
            this.cboLoaiKS = new System.Windows.Forms.ComboBox();
            this.label7 = new System.Windows.Forms.Label();
            this.cboDangKy = new System.Windows.Forms.ComboBox();
            this.label8 = new System.Windows.Forms.Label();
            this.txtMaKS = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.dtGui = new System.Windows.Forms.DateTimePicker();
            this.btnGui = new System.Windows.Forms.Button();
            this.dgvKS = new System.Windows.Forms.DataGridView();
            this.label10 = new System.Windows.Forms.Label();
            this.txtKSChon = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.dtPH = new System.Windows.Forms.DateTimePicker();
            this.label12 = new System.Windows.Forms.Label();
            this.numDiem = new System.Windows.Forms.NumericUpDown();
            this.label13 = new System.Windows.Forms.Label();
            this.txtGopY = new System.Windows.Forms.TextBox();
            this.btnGhiPH = new System.Windows.Forms.Button();
            this.btnDong = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDoan)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numTien)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKS)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDiem)).BeginInit();
            this.SuspendLayout();
            this.tabKT.SuspendLayout();
            this.tpTT.SuspendLayout();
            this.tpKS.SuspendLayout();
            this.tabKT.Name = "tabKT";
            this.tabKT.Location = new System.Drawing.Point(10, 10);
            this.tabKT.Size = new System.Drawing.Size(980, 560);
            this.tabKT.TabIndex = 0;
            this.Controls.Add(this.tabKT);
            this.tpTT.Name = "tpTT";
            this.tpTT.Text = "Thanh toán sau tour (đoàn)";
            this.tpTT.Padding = new System.Windows.Forms.Padding(3);
            this.tpTT.UseVisualStyleBackColor = true;
            this.tabKT.Controls.Add(this.tpTT);
            this.tpKS.Name = "tpKS";
            this.tpKS.Text = "Khảo sát khách hàng";
            this.tpKS.Padding = new System.Windows.Forms.Padding(3);
            this.tpKS.UseVisualStyleBackColor = true;
            this.tabKT.Controls.Add(this.tpKS);
            this.dgvDoan.Name = "dgvDoan";
            this.dgvDoan.Location = new System.Drawing.Point(10, 10);
            this.dgvDoan.Size = new System.Drawing.Size(950, 330);
            this.dgvDoan.AllowUserToAddRows = false;
            this.dgvDoan.AllowUserToDeleteRows = false;
            this.dgvDoan.ReadOnly = true;
            this.dgvDoan.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDoan.MultiSelect = false;
            this.dgvDoan.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDoan.RowHeadersVisible = false;
            this.dgvDoan.BackgroundColor = System.Drawing.SystemColors.Window;
            this.dgvDoan.TabIndex = 1;
            this.dgvDoan.SelectionChanged += new System.EventHandler(this.dgvDoan_SelectionChanged);
            this.tpTT.Controls.Add(this.dgvDoan);
            this.label1.Name = "label1";
            this.label1.Location = new System.Drawing.Point(10, 358);
            this.label1.AutoSize = true;
            this.label1.Text = "Số thanh toán";
            this.label1.TabIndex = 2;
            this.tpTT.Controls.Add(this.label1);
            this.txtSoTT.Name = "txtSoTT";
            this.txtSoTT.Location = new System.Drawing.Point(100, 355);
            this.txtSoTT.Size = new System.Drawing.Size(110, 23);
            this.txtSoTT.TabIndex = 3;
            this.tpTT.Controls.Add(this.txtSoTT);
            this.label2.Name = "label2";
            this.label2.Location = new System.Drawing.Point(300, 358);
            this.label2.AutoSize = true;
            this.label2.Text = "Phiếu đoàn";
            this.label2.TabIndex = 4;
            this.tpTT.Controls.Add(this.label2);
            this.txtSoDK.Name = "txtSoDK";
            this.txtSoDK.Location = new System.Drawing.Point(375, 355);
            this.txtSoDK.Size = new System.Drawing.Size(110, 23);
            this.txtSoDK.ReadOnly = true;
            this.txtSoDK.TabIndex = 5;
            this.tpTT.Controls.Add(this.txtSoDK);
            this.label3.Name = "label3";
            this.label3.Location = new System.Drawing.Point(520, 358);
            this.label3.AutoSize = true;
            this.label3.Text = "Ngày thanh toán";
            this.label3.TabIndex = 6;
            this.tpTT.Controls.Add(this.label3);
            this.dtTT.Name = "dtTT";
            this.dtTT.Location = new System.Drawing.Point(625, 355);
            this.dtTT.Size = new System.Drawing.Size(110, 23);
            this.dtTT.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtTT.CustomFormat = "dd/MM/yyyy";
            this.dtTT.TabIndex = 7;
            this.tpTT.Controls.Add(this.dtTT);
            this.label4.Name = "label4";
            this.label4.Location = new System.Drawing.Point(10, 395);
            this.label4.AutoSize = true;
            this.label4.Text = "Số tiền";
            this.label4.TabIndex = 8;
            this.tpTT.Controls.Add(this.label4);
            this.numTien.Name = "numTien";
            this.numTien.Location = new System.Drawing.Point(100, 392);
            this.numTien.Size = new System.Drawing.Size(150, 23);
            this.numTien.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            this.numTien.Maximum = new decimal(new int[] { 2000000000, 0, 0, 0 });
            this.numTien.Increment = new decimal(new int[] { 1000000, 0, 0, 0 });
            this.numTien.Value = new decimal(new int[] { 0, 0, 0, 0 });
            this.numTien.ThousandsSeparator = true;
            this.numTien.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numTien.TabIndex = 9;
            this.tpTT.Controls.Add(this.numTien);
            this.label5.Name = "label5";
            this.label5.Location = new System.Drawing.Point(300, 395);
            this.label5.AutoSize = true;
            this.label5.Text = "Ghi chú";
            this.label5.TabIndex = 10;
            this.tpTT.Controls.Add(this.label5);
            this.txtGhiChu.Name = "txtGhiChu";
            this.txtGhiChu.Location = new System.Drawing.Point(375, 392);
            this.txtGhiChu.Size = new System.Drawing.Size(330, 23);
            this.txtGhiChu.TabIndex = 11;
            this.tpTT.Controls.Add(this.txtGhiChu);
            this.btnThanhToan.Name = "btnThanhToan";
            this.btnThanhToan.Location = new System.Drawing.Point(700, 389);
            this.btnThanhToan.Size = new System.Drawing.Size(190, 28);
            this.btnThanhToan.Text = "Ghi nhận thanh toán";
            this.btnThanhToan.UseVisualStyleBackColor = true;
            this.btnThanhToan.TabIndex = 12;
            this.btnThanhToan.Click += new System.EventHandler(this.btnThanhToan_Click);
            this.tpTT.Controls.Add(this.btnThanhToan);
            this.label6.Name = "label6";
            this.label6.Location = new System.Drawing.Point(10, 18);
            this.label6.AutoSize = true;
            this.label6.Text = "Loại khách";
            this.label6.TabIndex = 13;
            this.tpKS.Controls.Add(this.label6);
            this.cboLoaiKS.Name = "cboLoaiKS";
            this.cboLoaiKS.Location = new System.Drawing.Point(80, 15);
            this.cboLoaiKS.Size = new System.Drawing.Size(80, 23);
            this.cboLoaiKS.FormattingEnabled = true;
            this.cboLoaiKS.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLoaiKS.TabIndex = 14;
            this.cboLoaiKS.SelectedIndexChanged += new System.EventHandler(this.cboLoaiKS_SelectedIndexChanged);
            this.tpKS.Controls.Add(this.cboLoaiKS);
            this.label7.Name = "label7";
            this.label7.Location = new System.Drawing.Point(190, 18);
            this.label7.AutoSize = true;
            this.label7.Text = "Đăng ký đã kết thúc";
            this.label7.TabIndex = 15;
            this.tpKS.Controls.Add(this.label7);
            this.cboDangKy.Name = "cboDangKy";
            this.cboDangKy.Location = new System.Drawing.Point(320, 15);
            this.cboDangKy.Size = new System.Drawing.Size(260, 23);
            this.cboDangKy.FormattingEnabled = true;
            this.cboDangKy.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDangKy.TabIndex = 16;
            this.tpKS.Controls.Add(this.cboDangKy);
            this.label8.Name = "label8";
            this.label8.Location = new System.Drawing.Point(620, 18);
            this.label8.AutoSize = true;
            this.label8.Text = "Mã KS";
            this.label8.TabIndex = 17;
            this.tpKS.Controls.Add(this.label8);
            this.txtMaKS.Name = "txtMaKS";
            this.txtMaKS.Location = new System.Drawing.Point(665, 15);
            this.txtMaKS.Size = new System.Drawing.Size(80, 23);
            this.txtMaKS.TabIndex = 18;
            this.tpKS.Controls.Add(this.txtMaKS);
            this.label9.Name = "label9";
            this.label9.Location = new System.Drawing.Point(770, 18);
            this.label9.AutoSize = true;
            this.label9.Text = "Ngày gửi";
            this.label9.TabIndex = 19;
            this.tpKS.Controls.Add(this.label9);
            this.dtGui.Name = "dtGui";
            this.dtGui.Location = new System.Drawing.Point(825, 15);
            this.dtGui.Size = new System.Drawing.Size(100, 23);
            this.dtGui.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtGui.CustomFormat = "dd/MM/yyyy";
            this.dtGui.TabIndex = 20;
            this.tpKS.Controls.Add(this.dtGui);
            this.btnGui.Name = "btnGui";
            this.btnGui.Location = new System.Drawing.Point(10, 50);
            this.btnGui.Size = new System.Drawing.Size(170, 28);
            this.btnGui.Text = "Gửi phiếu khảo sát";
            this.btnGui.UseVisualStyleBackColor = true;
            this.btnGui.TabIndex = 21;
            this.btnGui.Click += new System.EventHandler(this.btnGui_Click);
            this.tpKS.Controls.Add(this.btnGui);
            this.dgvKS.Name = "dgvKS";
            this.dgvKS.Location = new System.Drawing.Point(10, 90);
            this.dgvKS.Size = new System.Drawing.Size(950, 250);
            this.dgvKS.AllowUserToAddRows = false;
            this.dgvKS.AllowUserToDeleteRows = false;
            this.dgvKS.ReadOnly = true;
            this.dgvKS.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvKS.MultiSelect = false;
            this.dgvKS.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvKS.RowHeadersVisible = false;
            this.dgvKS.BackgroundColor = System.Drawing.SystemColors.Window;
            this.dgvKS.TabIndex = 22;
            this.dgvKS.SelectionChanged += new System.EventHandler(this.dgvKS_SelectionChanged);
            this.tpKS.Controls.Add(this.dgvKS);
            this.label10.Name = "label10";
            this.label10.Location = new System.Drawing.Point(10, 358);
            this.label10.AutoSize = true;
            this.label10.Text = "Phiếu chọn";
            this.label10.TabIndex = 23;
            this.tpKS.Controls.Add(this.label10);
            this.txtKSChon.Name = "txtKSChon";
            this.txtKSChon.Location = new System.Drawing.Point(85, 355);
            this.txtKSChon.Size = new System.Drawing.Size(100, 23);
            this.txtKSChon.ReadOnly = true;
            this.txtKSChon.TabIndex = 24;
            this.tpKS.Controls.Add(this.txtKSChon);
            this.label11.Name = "label11";
            this.label11.Location = new System.Drawing.Point(300, 358);
            this.label11.AutoSize = true;
            this.label11.Text = "Ngày phản hồi";
            this.label11.TabIndex = 25;
            this.tpKS.Controls.Add(this.label11);
            this.dtPH.Name = "dtPH";
            this.dtPH.Location = new System.Drawing.Point(395, 355);
            this.dtPH.Size = new System.Drawing.Size(110, 23);
            this.dtPH.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtPH.CustomFormat = "dd/MM/yyyy";
            this.dtPH.TabIndex = 26;
            this.tpKS.Controls.Add(this.dtPH);
            this.label12.Name = "label12";
            this.label12.Location = new System.Drawing.Point(580, 358);
            this.label12.AutoSize = true;
            this.label12.Text = "Điểm (1-5)";
            this.label12.TabIndex = 27;
            this.tpKS.Controls.Add(this.label12);
            this.numDiem.Name = "numDiem";
            this.numDiem.Location = new System.Drawing.Point(655, 355);
            this.numDiem.Size = new System.Drawing.Size(60, 23);
            this.numDiem.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numDiem.Maximum = new decimal(new int[] { 5, 0, 0, 0 });
            this.numDiem.Value = new decimal(new int[] { 5, 0, 0, 0 });
            this.numDiem.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numDiem.TabIndex = 28;
            this.tpKS.Controls.Add(this.numDiem);
            this.label13.Name = "label13";
            this.label13.Location = new System.Drawing.Point(10, 395);
            this.label13.AutoSize = true;
            this.label13.Text = "Góp ý";
            this.label13.TabIndex = 29;
            this.tpKS.Controls.Add(this.label13);
            this.txtGopY.Name = "txtGopY";
            this.txtGopY.Location = new System.Drawing.Point(85, 392);
            this.txtGopY.Size = new System.Drawing.Size(620, 23);
            this.txtGopY.TabIndex = 30;
            this.tpKS.Controls.Add(this.txtGopY);
            this.btnGhiPH.Name = "btnGhiPH";
            this.btnGhiPH.Location = new System.Drawing.Point(700, 389);
            this.btnGhiPH.Size = new System.Drawing.Size(190, 28);
            this.btnGhiPH.Text = "Ghi nhận góp ý";
            this.btnGhiPH.UseVisualStyleBackColor = true;
            this.btnGhiPH.TabIndex = 31;
            this.btnGhiPH.Click += new System.EventHandler(this.btnGhiPH_Click);
            this.tpKS.Controls.Add(this.btnGhiPH);
            this.btnDong.Name = "btnDong";
            this.btnDong.Location = new System.Drawing.Point(890, 580);
            this.btnDong.Size = new System.Drawing.Size(100, 28);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.TabIndex = 32;
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Controls.Add(this.btnDong);
            ((System.ComponentModel.ISupportInitialize)(this.dgvDoan)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numTien)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKS)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDiem)).EndInit();
            this.tabKT.ResumeLayout(false);
            this.tpTT.ResumeLayout(false);
            this.tpKS.ResumeLayout(false);
            //
            // FrmKetThucKhaoSat
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1000, 620);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FrmKetThucKhaoSat";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Kết thúc tour - khảo sát";
            this.Load += new System.EventHandler(this.FrmKetThucKhaoSat_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TabControl tabKT;
        private System.Windows.Forms.TabPage tpTT;
        private System.Windows.Forms.TabPage tpKS;
        private System.Windows.Forms.DataGridView dgvDoan;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtSoTT;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtSoDK;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.DateTimePicker dtTT;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.NumericUpDown numTien;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox txtGhiChu;
        private System.Windows.Forms.Button btnThanhToan;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.ComboBox cboLoaiKS;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.ComboBox cboDangKy;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox txtMaKS;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.DateTimePicker dtGui;
        private System.Windows.Forms.Button btnGui;
        private System.Windows.Forms.DataGridView dgvKS;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.TextBox txtKSChon;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.DateTimePicker dtPH;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.NumericUpDown numDiem;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.TextBox txtGopY;
        private System.Windows.Forms.Button btnGhiPH;
        private System.Windows.Forms.Button btnDong;
    }
}
